###########
# site.title, site.url, site.author.name

title:   'Vinay Patel'
author:
  name:  'Vinay Patel'

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: ''
url:  'http://www.vinayvinay.com'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md

plugins:
  - jekyll-sitemap

safe: true
lsi: false
